name: Test copypedeps with MSYS2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up MSYS2 with the necessary toolchain
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          location: D:\
          install: >-
            mingw-w64-x86_64-toolchain
            base-devel
            zip
            git
            mingw-w64-x86_64-wget
            mingw-w64-x86_64-unzip

      # Build the simple console project
      - name: Build C++ project
        shell: msys2 {0}
        run: |
          g++ -o hello.exe hello.cpp

      # Download the latest 64-bit binary release of pedeps
      - name: Download pedeps latest 64-bit binary
        shell: msys2 {0}
        run: |
          # Get the download URL for the latest 64-bit binary release
          LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/brechtsanders/pedeps/releases/latest \
            | grep "browser_download_url.*win64.zip" \
            | head -n 1 \
            | cut -d '"' -f 4)

          # Download the file
          wget "$LATEST_RELEASE_URL" -O pedeps-latest.zip
          unzip pedeps-latest.zip -d pedeps

      # Run copypedeps on hello.exe
      - name: Run copypedeps
        shell: msys2 {0}  # Use MSYS2 shell
        run: |
          ./pedeps/copypedeps.exe -r -n -v ./hello.exe ./bin/

      # Upload the result as an artifact to review dependencies
      - uses: actions/upload-artifact@v4
        with:
          name: hello-dependencies
          path: ./bin/
