name: Test copypedeps with MSYS2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up MSYS2 with the necessary toolchain
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          location: D:\
          install: >-
            mingw-w64-x86_64-toolchain
            base-devel
            zip
            unzip
            git
            mingw-w64-x86_64-wget
            jq

      # Build the simple console project
      - name: Build C++ project
        shell: msys2 {0}  # Use MSYS2 shell
        run: |
          g++ -o hello.exe hello.cpp

      # Get the latest release version and construct the download URL
      - name: Get Latest Release Version
        id: get_latest_release
        shell: msys2 {0}  # Use MSYS2 shell
        run: |
          # Fetch the latest release version from GitHub API
          LATEST_VERSION=$(curl -s https://api.github.com/repos/brechtsanders/pedeps/releases/latest | jq -r .tag_name)
          echo "Latest version is $LATEST_VERSION"

          # Construct the download URL
          DOWNLOAD_URL="https://github.com/brechtsanders/pedeps/releases/download/${LATEST_VERSION}/pedeps-${LATEST_VERSION}-win64.zip"
          echo "DOWNLOAD_URL=${DOWNLOAD_URL}" >> $GITHUB_ENV

      # Download and extract the specific pedeps release
      - name: Download and extract pedeps
        shell: msys2 {0}  # Use MSYS2 shell
        run: |
          # Use the URL from the previous step to download the file
          wget $DOWNLOAD_URL -O pedeps-latest.zip

          # Unzip the downloaded file
          unzip pedeps-latest.zip -d pedeps

          # List contents of the pedeps directory to verify
          ls -R pedeps

      # List files in the working directory
      - name: List files in the working directory
        shell: msys2 {0}  # Use MSYS2 shell
        run: |
          ls -l

      # Run copypedeps on hello.exe
      - name: Run copypedeps
        shell: msys2 {0}  # Use MSYS2 shell
        run: |
          ./pedeps/copypedeps.exe -r -n -v ./hello.exe ./bin/

      # Upload the result as an artifact to review dependencies
      - uses: actions/upload-artifact@v4
        with:
          name: hello-dependencies
          path: ./bin/
